### ISSUE TITLE
Crashes on 1.19.3

### ISSUE THREAD

**Issue by Linventor** [AliahX/Mixtape#1]
runs fine without mod installed.
https://mclo.gs/rVUtyrM

**Comment by AliahX** [comment]
Seeing as I haven't made a 1.19.3 version of mixtape yet, that would make sense. Would you like me to compile one this afternoon?

**Comment by Linventor** [comment]
That would be appreciated!

**Comment by OoLunar** [comment]
I would also love to have a release available for 1.19.3!

**Comment by AliahX** [comment]
Sorry for the wait. I was able to port the mod today, tomorrow I will test it to make sure all of the features work properly, and then i'll upload it.

**Comment by AliahX** [comment]
Done! [https://github.com/AliahX/Mixtape/releases/tag/v1.3](https://github.com/AliahX/Mixtape/releases/tag/v1.3) If you guys ever have any suggestions or issues or just anything you think I could improve on for mixtape, pleeeeeeease let me know!
